### ISSUE TITLE
Adding accellibandroid

### ISSUE THREAD

**Issue by foresterre** [foresterre/ContextProject#23]
We will try to add AccelLibAndroid (By Job Becht, Wouter Groen, Olivier Hokke, Eric Rijnboutt) so we can more easily determine whether a player is either "Resting", "Walking", "Running" or "Cheating".

@Surskit 
@foresterre

**Comment by foresterre** [comment]
Currently trying to do this by interfacing from the core module to the android & desktop modules.
Up next is to interface it backwards to the core module.

**Comment by sirpolomotro** [comment]
Implemented after #51
