### ISSUE TITLE
Text not wrapping.

### ISSUE THREAD

**Issue by Jurgenvs** [foresterre/ContextProject#27]
When text does out of the boundaries of the stage it is not being wrapped. This results in the text not being completely visible.

**Comment by NickTUD** [comment]
Maybe a handy link: http://stackoverflow.com/questions/18557448/libgdx-how-to-get-a-label-with-wrapped-text

**Comment by sirpolomotro** [comment]
Should be fixed with new text font. Not confirmed that it is fixed yet.
