### ISSUE TITLE
StrollTimer keeps running after restarting the game.

### ISSUE THREAD

**Issue by Jurgenvs** [foresterre/ContextProject#32]
We need to determine what we want to do with a 'running' stroll. Do you restart the stroll, do you continue from where you left or is the stroll thrown away?

**Comment by sirpolomotro** [comment]
If we want to continue from where we left of it kind of conflicts with the 5 min activity statement.
However if we want it to be able to resume an stroll, all the rewards have to be stored in the preferences after an event has ended.
