### ISSUE TITLE
Maven -> Gradle

### ISSUE THREAD

**Issue by foresterre** [foresterre/ContextProject#4]
We are redoing the setup of the project to Gradle instead of Maven.
The most important reason for this is libgdx, since its support of Maven is not good enough (it takes a lot of time to setup and maintain).

* Base libgdx project
* Configure Travis-CI to work properly with Gradle
* Add static analysis tools to Gradle build
  * PMD
  * Find bugs
  * CheckStyle
* Merge the deliverables, old project and new project setup properly.

**Comment by foresterre** [comment]
The static analysis tools are now all integrated with gradle.
If pull request #10 will be accepted, this ticket is probably completed.

**Comment by Jurgenvs** [comment]
Should all work now. Gj Martijn
