### ISSUE TITLE
Local storage of collection

### ISSUE THREAD

**Issue by foresterre** [foresterre/ContextProject#44]
When a player plays the game and receives rewards, he/she wants to keep this data available after exiting the application. This data, a game save should be stored on the local file system.

requirements
* should be able to store the collectibles collected in a local file.
* should be able to read data about collectibles collected from a local file.
* should work on both the desktop and android

nice to have
* should be able to encrypt and decrypt this game save data -> Currently functionality is more important. 

literature
* http://json.org/
* https://github.com/libgdx/libgdx/wiki/File-handling
* http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Json.html
* https://github.com/libgdx/libgdx/wiki/Reading-%26-writing-json

problems
* Libgdx's json is not so well documented, throws a lot of undocumented exceptions
* jackson is no longer actively developed
* because Collectible is an abstract class, jackson can not automatically deserialize. However when manually marking the types for (de)serialization; still exceptions are thrown

solutions
* use java's serializable
* possibly if JSON is really wanted, use the jackson or gson library.

current implementation
* uses java's serializable and libgdx's write file (to be compatible on both the desktop (for debugging) and android (debug & production)

**Comment by foresterre** [comment]
The current version uses (java's build in) serialization. See 301a36b0 and earlier commits.

* ~~ should be able to store the collectibles collected to a local file.~~
* ~~ should be able to read data about collectibles collected from a local file. ~~
* ~~ should work on both the desktop and android ~~ (d18e9b5 fixed android)

**Comment by sirpolomotro** [comment]
Will probably not be needed because of local server implementation.

**Comment by foresterre** [comment]
see #58
