### ISSUE TITLE
Local server

### ISSUE THREAD

**Issue by foresterre** [foresterre/ContextProject#58]
### The idea (not before lock)

Our current implementation has a separation between the local activities and the multiplayer activities.
This also means, different ways to storage of achieved rewards.
Locally the progression is stored as a serialized file.
On the server, the group progression is stored as a sqlite database. 

The idea is to remove the local storage completely (along with other client<>server separated components).
Instead we will use a local server on the device; which will store, for example, the offline user progression in a local sqlite database.

##### Pro's
* Unified implementations for both client- / server-side (reuse of components)
* Less compatibility issue's (against serialization)
 
##### Con's
* New implementation (thus time)

#### Current setup

<pre><code>
######################               #####################################
# device (Local)     #  -----------  # local file system (progression)   #
######################               #####################################      
           |
           |
           | net
           |
           |
###############               #####################################
# server      #  -----------  # sqlite (group progression)        #
###############               #####################################      
</code></pre>

#### Proposed setup

<pre><code>
#########################
# device (local)        #
#        ################               #####################################
#        #    server    #  -----------  # sqlite (personal progression)     #
#        ################               #####################################
#########################
           |
           |
           | net
           |
           |
###############               #####################################
# server      #  -----------  # sqlite (group progression)        #
###############               #####################################      
</code></pre>

@foresterre
@sirpolomotro

**Comment by Jurgenvs** [comment]
Local server is functioning. Also works on android.
